### ISSUE TITLE
Content: Create content for the contribute page of AnitaB-org

### ISSUE THREAD

**Issue by rutvi18** [anitab-org/anitab-org.github.io#185] opened 2020-12-26 15:21 UTC
**Description**

As a user,
Would like to have an engaging description of each header in contribute page. Changes to be done to issue #169 

**Mock**

![anitab](https://user-images.githubusercontent.com/43277445/103154095-5d050a80-47bb-11eb-8543-e135e8ba0972.png)

**Acceptance Criteria**

- [ ] The description should be engaging and relevant to the headers.

**Criteria for completion**

- [ ] Approved by at-least one mentor
- [ ] All the requirements are completed

**Estimate Time**

2-3 days

**Comment by sankha555** [comment] 2020-12-27 08:06
Hello @rutvi18,
I would like to work on this issue. Could I please be assigned this? Basically, I need to write and code some content for the headings in the contribute page right (eg. new to open source, ways to contribute, open source programs etc.) ? Also, do I need to make changes to PR#169 or should I start off a new page for the contribution link. A brief walkthrough for the task and relevant files from you would be really helpful. Thanks!

**Comment by rutvi18** [comment] 2020-12-27 13:39
@sankha555 sure....will assign you the issue.
[Resource](https://github.com/rutvi18/anitab-org.github.io/tree/rutvi_contibute)
You can pull a PR instead of making direct changes to #169. Once it is reviewed, it will be merged with  #169

**Comment by nandini45** [comment] 2020-12-27 14:16
@rutvi18  this issue has  been created and there is a PR for that. 
And moreover after creating a issue. Any project managers should confirm the issue whether it is required or not then only you can assign it to anyone.

**Comment by rutvi18** [comment] 2020-12-27 14:18
@nandini45 ok thanks

**Closed** 2020-12-27 14:23 UTC

**Comment by nandini45** [comment] 2020-12-27 14:25
@sankha555 sorry for this.
The issue has been created and a PR is there for it..
Perhaps you can look for other issues to work on. 
Thanks

**Comment by nandini45** [comment] 2020-12-27 14:27
@rutvi18  can you tell me one thing the issue is about new to open source section or the other one too??

**Comment by sankha555** [comment] 2020-12-27 14:29
@nandini45 Thanks for the clarification. I'll try to find some other issues to work on using the issue tracker. Also, if you know of some issue that might require contribution now and could kindly direct me to it, it would be great help. Thanks!

**Comment by nandini45** [comment] 2020-12-27 14:31
@sankha555 sure give me a moment.can u mention ur preferred  language??

**Comment by rutvi18** [comment] 2020-12-27 14:32
@nandini45 it is for the entire page....as I have made a PR for the contribute page. And didn't know the issue already exists.

**Comment by rutvi18** [comment] 2020-12-27 14:33
@nandini45 And also can u tell should I now merge that PR with mine, right?

**Comment by sankha555** [comment] 2020-12-27 14:33
Ya sure. I am experienced in and mostly work using Python and specifically use Django framework for web development applications. Would love to contribute in these tech stacks. Thanks!

**Comment by nandini45** [comment] 2020-12-27 14:35
Ok the page content was too much so it was  divided ibto 2 3 sections. 
The content in the PR i gave u is for one section.
The content for the other is yet to be merged. Their is a PR but we have to merge it yet. @rutvi18 
So  idk to be true probably u can take the content from the pr and then merge??
Just  a suggestion

**Comment by rutvi18** [comment] 2020-12-27 14:37
@nandini45 ok...thanks a lot :)

**Comment by nandini45** [comment] 2020-12-27 14:38
@sankha555  this repo uses djano framework mainly.. there are loads of issue for u
https://github.com/anitab-org/mentorship-backend/issues
Happy coding!!

**Comment by sankha555** [comment] 2020-12-27 14:40
Thanks a lot @nandini45 ! :)
