### ISSUE TITLE
Typo in Archive page

### ISSUE THREAD

**Issue by udyanojha** [anitab-org/anitab-org.github.io#360] opened 2022-06-20 22:58 UTC
### To Reproduce
1. Go to '[https://anitab-org.github.io/](https://anitab-org.github.io/)'
2. Click on Projects
3. Scroll down to "Archived Projects" section
4. See description of section with typo in word "archieved"

### Expected behavior

Should have "archived" instead of "archieved"

### Screenshots

![image](https://user-images.githubusercontent.com/51847297/174686577-95e4d205-81e6-4dd5-8a6c-b5d066e0c2c1.png)

### Additional context
This applies to any device where this website can be accessed.

**Comment by udyanojha** [comment] 2022-06-20 23:04
Hi!
I'm new to open source and would like to contribute.

**Comment by isabelcosta** [comment] 2022-06-21 21:43
@udyanojha thank you for reporting this! However, this ticket is a duplicate of https://github.com/anitab-org/anitab-org.github.io/issues/355 which is already assigned to a contributor.

Feel free to tag me if you find another **available** task you'd like to contribute to

**Closed by isabelcosta** 2022-06-21 21:43 UTC
