### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sagar-barapatre** [anitab-org/anitab-org.github.io#204] opened 2021-01-28 04:29 UTC
### Describe the solution you'd like
Dark mode has gained popularity thanks to the addition of OS-level dark modes in iOS, macOS, Android, and Windows. Regardless of the hype, dark mode has some real benefits:
- Less blue light could mean less disruption to the body’s sleep cycle if using the display in the evening.
- Light-on-dark text can be easier to read for some people, while others find it harder. Users should be able to choose between light and dark mode.

### Alternatives you've considered
Will move the colours to the assets and made them invert for dark mode so it looks more like what GitHub does when it's in dark mode.

### Potential downsides
Each component/page/feature needs to be tested in both light and dark mode. This duplicates the testing effort.

If someone approves this. Please assign this to me. I would like to work on this

**Comment by Rahulm2310** [comment] 2021-01-28 18:06
@sagar-barapatre Thanks for showing interest in the project. Although, when contributing to a open source project, it is suggested to wait for a maintainer to approve a issue/feature request before creating a pull request for the same. Please have a look at the contributing guidelines [here](https://github.com/anitab-org/anitab-org.github.io/blob/develop/CONTRIBUTING.md). 🙂

**Comment by vj-codes** [comment] 2021-01-28 18:10
@sagar-barapatre hey this issue is a valid feature. We do want to include but its a future work.For now we don't need it.
We need to work on the website for now.
You can look for issues in the repository:)
I will close this and also a duplicate of #179

**Closed by vj-codes** 2021-01-28 18:10 UTC
